%% Extract element typetag from element record
%  Arguments:
%    elrecord - vector of integer values as generated by GMSH.
function [typetag] = mp_gmsh_element_typetag(elrecord)
  typetag = sprintf('type_%d', elrecord(2));
end
