mp_test_register('bc2tag', 'Test conversion from BcType to FlagSHyp tag');
bc2tag = mp.exports.flagshyp.bc2tag;
mp_test_assert_equal(0, bctag(mp.BcType.NotSet));
mp_test_assert_equal(1, bctag(mp.BcType.FixityX));
mp_test_assert_equal(2, bctag(mp.BcType.FixityY));
mp_test_assert_equal(3, bctag(mp.BcType.FixityXY));
mp_test_assert_equal(4, bctag(mp.BcType.FixityZ));
mp_test_assert_equal(5, bctag(mp.BcType.FixityXZ));
mp_test_assert_equal(6, bctag(mp.BcType.FixityYZ));
mp_test_assert_equal(7, bctag(mp.BcType.Fixity));
